"""empty message

Revision ID: 8382c48eba87
Revises: d55cb75a16e1
Create Date: 2020-08-18 12:33:44.748820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8382c48eba87'
down_revision = 'd55cb75a16e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_body', table_name='post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_body', 'post', ['body'], unique=1)
    # ### end Alembic commands ###
